# Generated by Django 4.1.7 on 2023-03-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.IntegerField(blank=True, null=True)),
                ('cat2', models.IntegerField(blank=True, null=True)),
                ('cat3', models.IntegerField(blank=True, null=True)),
                ('final_exam_grade', models.IntegerField(default=0)),
                ('std_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.student')),
                ('unit_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.unit')),
            ],
        ),
    ]
