# Generated by Django 4.1.7 on 2023-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_alter_unit_unit_code_alter_unit_unit_title_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='std_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='unit_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
