# Generated by Django 4.1.7 on 2023-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_alter_class_std_name_alter_class_unit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=200)),
                ('std_regno', models.CharField(max_length=200)),
                ('std_course', models.CharField(max_length=200)),
                ('unit_code', models.CharField(max_length=200)),
            ],
        ),
    ]
