# Generated by Django 4.1.7 on 2023-03-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_classstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(blank=True, max_length=200, null=True)),
                ('cat1', models.IntegerField(blank=True, null=True)),
                ('cat2', models.IntegerField(blank=True, null=True)),
                ('cat3', models.IntegerField(blank=True, null=True)),
                ('final_exam_grade', models.IntegerField(default=0)),
            ],
        ),
    ]
